webserver/routes/web.php
                Route::get('/', 'BroadcastController@index')->name('index');
                Route::get('getBroadcastCalendar', 'BroadcastController@getBroadcastCalendar')->name('getBroadcastCalendar');
                Route::get('getBroadcastList', 'BroadcastController@getBroadcastList')->name('getBroadcastList');
                Route::get('create', 'BroadcastController@create')->name('create');
                Route::post('/', 'BroadcastController@store')->name('store');

                Route::group(['prefix'=>'{broadcastId}'], function(){
                    Route::get('/', 'BroadcastController@show')->name('show');
                    Route::delete('/', 'BroadcastController@delete')->name('delete');
                });
            });

            Route::group(['as'=>'messagesPool.', 'prefix'=>'messagesPool', 'namespace'=>'Deployment'], function(){
                Route::get('/', 'MessagesPoolController@index')->name('index');
                Route::get('getMessages', 'MessagesPoolController@getMessages')->name('getMessages');
                Route::get('create', 'MessagesPoolController@create')->name('create');
                Route::post('store/message', 'MessagesPoolController@storeMessage')->name('storeMessage');
                Route::post('store/template', 'MessagesPoolController@storeTemplate')->name('storeTemplate');
                Route::get('queryForSelect', 'MessagesPoolController@queryForSelect')->name('queryForSelect');

                Route::group(['prefix'=>'{messageId}'], function(){
                    Route::get('/', 'MessagesPoolController@show')->name('show');
                    Route::get('edit', 'MessagesPoolController@edit')->name('edit');
                    Route::post('newMessageVersion', 'MessagesPoolController@newMessageVersion')->name('newMessageVersion');
                    Route::post('newTemplateVersion', 'MessagesPoolController@newTemplateVersion')->name('newTemplateVersion');
                    Route::post('switchVersion', 'MessagesPoolController@switchVersion')->name('switchVersion');
                    Route::delete('deleteAll', 'MessagesPoolController@deleteAll')->name('deleteAll');
                    Route::get('getMessage', 'MessagesPoolController@getMessage')->name('getMessage');
                });
            });

            Route::group(['as'=>'keywords.', 'prefix'=>'keywords', 'namespace'=>'Deployment'], function(){
                Route::get('/', 'KeywordController@index')->name('index');
                Route::get('getKeywords', 'KeywordController@getKeywords')->name('getKeywords');
                Route::get('getChartData', 'KeywordController@getChartData')->name('getChartData');
                Route::get('create', 'KeywordController@create')->name('create');
                Route::get('getRichmenu', 'KeywordController@getRichmenu')->name('getRichmenu');
                Route::post('/', 'KeywordController@store')->name('store');
                Route::get('queryForSelect', 'KeywordController@queryForSelect')->name('queryForSelect');

                Route::group(['prefix'=>'{keywordId}'], function(){
                    Route::get('/', 'KeywordController@show')->name('show');
                    Route::get('edit', 'KeywordController@edit')->name('edit');
                    Route::post('newVersion', 'KeywordController@newVersion')->name('newVersion');
                    Route::post('switchVersion', 'KeywordController@switchVersion')->name('switchVersion');
                    Route::post('toggleActive', 'KeywordController@toggleActive')->name('toggleActive');
                    Route::delete('deleteAll', 'KeywordController@deleteAll')->name('deleteAll');
                });
            });

            Route::group(['as'=>'scripts.', 'prefix'=>'scripts', 'namespace'=>'Deployment'], function(){
                Route::get('/', 'ScriptController@index')->name('index');
                Route::get('getScripts', 'ScriptController@getScripts')->name('getScripts');
                Route::get('getChartData', 'ScriptController@getChartData')->name('getChartData');
                Route::get('create', 'ScriptController@create')->name('create');
                Route::post('/', 'ScriptController@store')->name('store');
                Route::get('queryForSelect', 'ScriptController@queryForSelect')->name('queryForSelect');

                Route::group(['prefix'=>'{scriptId}'], function(){
                    Route::get('/', 'ScriptController@show')->name('show');
                    Route::get('edit', 'ScriptController@edit')->name('edit');
                    Route::post('newVersion', 'ScriptController@newVersion')->name('newVersion');
                    Route::post('switchVersion', 'ScriptController@switchVersion')->name('switchVersion');
                    Route::post('toggleActive', 'ScriptController@toggleActive')->name('toggleActive');
                    Route::delete('deleteAll', 'ScriptController@deleteAll')->name('deleteAll');
                });
            });

            Route::group(['as'=>'liffs.', 'prefix'=>'liffs', 'namespace'=>'Deployment'], function(){
                Route::get('/', 'LiffController@index')->name('index');
                Route::get('getLiffs', 'LiffController@getLiffs')->name('getLiffs');

                Route::group(['prefix'=>'{liffId}'], function(){
                    Route::delete('/', 'LiffController@delete')->name('delete');
                });
            });

            Route::group(['as'=>'tags.', 'prefix'=>'tags', 'namespace'=>'Deployment'], function(){
                Route::get('/', 'TagController@index')->name('index');
                Route::get('getTags', 'TagController@getTags')->name('getTags');

                Route::group(['prefix'=>'{tagId}'], function(){
                    Route::get('/', 'TagController@show')->name('show');
                    Route::get('getChartData', 'TagController@getChartData')->name('getChartData');
                    Route::post('name', 'TagController@name')->name('name');
                });
            });

            Route::group(['as'=>'users.', 'prefix'=>'users', 'namespace'=>'Deployment'], function(){
                Route::get('/', 'UserController@index')->name('index');
                Route::get('getUsers', 'UserController@getUsers')->name('getUsers');
                Route::get('queryForSelect', 'UserController@queryForSelect')->name('queryForSelect');

                Route::group(['prefix'=>'{userId}'], function(){
                    Route::get('/', 'UserController@show')->name('show');
                    Route::get('getHistory', 'UserController@getHistory')->name('getHistory');
                });
            });

            Route::group(['as'=>'groups.', 'prefix'=>'groups', 'namespace'=>'Deployment'], function(){
                Route::get('/', 'GroupController@index')->name('index');
                Route::get('create', 'GroupController@create')->name('create');
                Route::get('getTags', 'GroupController@getTags')->name('getTags');
                Route::get('getUsers', 'GroupController@getUsers')->name('getUsers');
                Route::post('/', 'GroupController@store')->name('store');
                Route::get('getGroups', 'GroupController@getGroups')->name('getGroups');
                Route::get('queryForSelect', 'GroupController@queryForSelect')->name('queryForSelect');

                Route::group(['prefix'=>'{groupId}'], function(){
                    Route::get('/', 'GroupController@show')->name('show');
                    Route::post('sync', 'GroupController@sync')->name('sync');
                    Route::get('getGroupUsers', 'GroupController@getGroupUsers')->name('getGroupUsers');
                });
            });

            Route::group(['as'=>'categories.', 'prefix'=>'categories', 'namespace'=>'Deployment'], function(){
                Route::get('/', 'CategoryController@index')->name('index');
                Route::post('/', 'CategoryController@store')->name('store');
                Route::post('classify', 'CategoryController@classify')->name('classify');
                Route::get('queryForSelect', 'CategoryController@queryForSelect')->name('queryForSelect');

                Route::group(['prefix'=>'{categoryId}'], function(){
                    Route::post('name', 'CategoryController@name')->name('name');
                    Route::delete('delete', 'CategoryController@delete')->name('delete');
                });
            });

            Route::group(['as'=>'chatroom.', 'prefix'=>'chatroom', 'namespace'=>'Deployment'], function(){
                Route::get('/', 'ChatroomController@index')->name('index');
                Route::post('imageUpload', 'ChatroomController@imageUpload')->name('imageUpload');
            });

            Route::group(['as'=>'tables.', 'prefix'=>'tables', 'namespace'=>'Deployment'], function(){
                Route::get('/', 'TableController@index')->name('index');
                Route::get('getTables', 'TableController@getTables')->name('getTables');
                Route::get('create', 'TableController@create')->name('create');
                Route::post('/', 'TableController@store')->name('store');
                Route::get('queryForSelect', 'TableController@queryForSelect')->name('queryForSelect');

                Route::group(['prefix'=>'{tableId}'], function(){
                    Route::get('/', 'TableController@show')->name('show');
                    Route::get('getRows', 'TableController@getRows')->name('getRows');
                    Route::delete('delete', 'TableController@delete')->name('delete');
                    Route::get('redeem', 'TableController@redeem')->name('redeem');
                });
            });

        });
    });

    //file
    Route::group(['as'=>'file.', 'prefix'=>'file'], function(){
        Route::group(['prefix'=>'{file}'], function(){
            Route::get('download', 'FileController@download')->name('download');
        });

webserver/app/Models/Platform/Solution/_4/AutoAnswer.php
<?php

namespace App\Models\Platform\Solution\_4;

use Hoyvoy\CrossDatabase\Eloquent\Model;

// Trait
use App\Models\Platform\Solution\_4\basic\MessageTrait;

class AutoAnswer extends Model
{

    use MessageTrait;

    protected $connection = 'solution_4';
    protected $table = 'auto_answers';
    protected $guarded = ['id'];

    protected $casts = [
        'messages' => 'object',
        'messages_form_data' => 'object',
    ];

    public function template()
    {
        return $this->belongsTo('App\Models\Platform\Solution\_4\Message', 'template_id', 'parent_id')
        ->orderBy('is_current_version', 'desc')
        ->orderBy('id', 'desc')
        ->limit(1);
    }

    public function periods()
    {
        return $this->morphMany('App\Models\Platform\Solution\_4\Period', 'periodable');
    }

    public function images()
    {
        return $this->morphToMany('App\Models\Platform\Solution\_4\Image', 'imageable');
    }

    public function videos()
    {
        return $this->morphToMany('App\Models\Platform\Solution\_4\Video', 'videoable');
    }

    public function tags()
    {
        return $this->morphMany('App\Models\Platform\Solution\_4\Tag', 'taggable');
    }

}

webserver/app/Models/Platform/Solution/_4/Broadcast.php
<?php

namespace App\Models\Platform\Solution\_4;

use DB;
use Hoyvoy\CrossDatabase\Eloquent\Model;

// Model
use App\Models\Platform\Solution\_4\Richmenu;

// Trait
use App\Models\Platform\Solution\_4\basic\MessageTrait;

// Helper
use App\Helpers\Solution\_4\Message\SendHelper;

class Broadcast extends Model
{

    use MessageTrait;

    protected $connection = 'solution_4';
    protected $table = 'broadcasts';
    protected $guarded = ['id'];

    protected $casts = [
        'groups_id' => 'object',
        'users_id' => 'object',
        'messages' => 'object',
        'messages_form_data' => 'object',
        'appointed_at' => 'datetime',
    ];

    /* ========== relations ========== */

    public function images()
    {
        return $this->morphToMany('App\Models\Platform\Solution\_4\Image', 'imageable');
    }

    public function videos()
    {
        return $this->morphToMany('App\Models\Platform\Solution\_4\Video', 'videoable');
    }

    public function tags()
    {
        return $this->morphMany('App\Models\Platform\Solution\_4\Tag', 'taggable');
    }

    public function category()
    {
        return $this->morphToMany('App\Models\Platform\Solution\_4\Category', 'categoryable')->where('categories.categoryable_type', 'App\Models\Platform\Solution\_4\Broadcast')->limit(1);
    }

    /* ========== attributes ========== */

    public static function shouldVersion()
    {
        return false;
    }

    /* ========== functions ========== */

    public function deleteCompletely()
    {
        DB::connection('solution_4')
        ->table('tags')
        ->where('taggable_id', $this->id)
        ->where('taggable_type', 'App\Models\Platform\Solution\_4\Broadcast')
        ->delete();

        $this->category()->detach();

        $this->images->each(function($image){
            $image->deleteCompletely();
        });

        return $this->delete();
    }
}

webserver/app/Models/Platform/Solution/_4/Category.php
<?php

namespace App\Models\Platform\Solution\_4;

use Hoyvoy\CrossDatabase\Eloquent\Model;

class Category extends Model
{

    protected $connection = 'solution_4';
    protected $table = 'categories';
    protected $guarded = ['id'];

    public function categoryables()
    {
        return $this->morphedByMany($this->categoryable_type, 'categoryable');
    }

}

webserver/app/Models/Platform/Solution/_4/Group.php
<?php

namespace App\Models\Platform\Solution\_4;

use DB;
use Hoyvoy\CrossDatabase\Eloquent\Model;

class Group extends Model
{
    protected $connection = 'solution_4';
    protected $table = 'groups';
    protected $guarded = ['id'];

    protected $casts = [
        'circles' => 'object',
        'add_users_id' => 'object',
        'remove_users_id' => 'object',
    ];

    public function users()
    {
        return $this->belongsToMany('App\Models\Platform\Solution\_4\User');
    }


}

webserver/app/Models/Platform/Solution/_4/Image.php
<?php

namespace App\Models\Platform\Solution\_4;

use DB;
use Storage;
use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    protected $connection = 'solution_4';
    protected $table = 'images';
    protected $guarded = ['id'];

    public function deleteCompletely()
    {
        if($this->disk == 'asset'){
            if(file_exists($this->path)) unlink($this->path);
        }else{
            Storage::disk($this->disk)->delete($this->path);
        }

        DB::connection('solution_4')->table('imageables')->where('image_id', $this->id)->delete();
        return $this->delete();
    }

    // 取得網址
    public function getUrl()
    {
        return $this->disk == 'asset' ? asset($this->path) : Storage::disk($this->disk)->url($this->path);
    }
}

webserver/app/Models/Platform/Solution/_4/Log.php
<?php

namespace App\Models\Platform\Solution\_4;

use Hoyvoy\CrossDatabase\Eloquent\Model;

// Model
use App\Models\Platform\Solution\Deployment;

class Log extends Model
{
    protected $connection = 'solution_4';
    protected $table = 'logs';
    protected $guarded = ['id'];

    protected $casts = [
        'messages' => 'object',
    ];

    public function user()
    {
        return $this->belongsTo('App\Models\Platform\Solution\_4\User');
    }

}

webserver/app/Models/Platform/Solution/_4/Table.php
<?php

namespace App\Models\Platform\Solution\_4;

use DB;
use Hoyvoy\CrossDatabase\Eloquent\Model;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;

class Table extends Model
{

    protected $connection = 'solution_4';
    protected $table = 'tables';
    protected $guarded = ['id'];

    protected $casts = [
        'editable_columns' => 'array',
        'settings' => 'object',
    ];

    /* ========== relations ========== */

    public function category()
    {
        return $this->morphToMany('App\Models\Platform\Solution\_4\Category', 'categoryable')->where('categories.categoryable_type', 'App\Models\Platform\Solution\_4\Keyword')->limit(1);
    }

    /* ========== attributes ========== */

    public static function shouldVersion()
    {
        return false;
    }

    public function getColumnList()
    {
        $orders = ['user_id', 'redeemed_at', 'redemption_url', 'staff_member_id', 'qrcode_url', 'created_at', 'updated_at'];
        return collect(Schema::Connection($this->connection)->getColumnListing($this->table_name))->sortBy(function($column) use($orders){
            if($column == 'id') return -1;

            $index = array_search($column, $orders);
            return $index ? $index : 0;
        })->values();
    }

    /* ========== functions ========== */

    public function getDataCounts()
    {
        return DB::connection($this->connection)
        ->table($this->table_name)
        ->count('id');
    }

    public function deleteCompletely()
    {
        $solution4Connection = DB::connection('solution_4');
        $solution4Connection->beginTransaction();

        try{

            $this->deleted_at = date('Y-m-d H:i:s');
            $this->save();

            Schema::connection('solution_4')->dropIfExists($this->table_name);

            $this->category()->detach();

            $solution4Connection->commit();
            return true;

        }catch(\Exception $ex){
            \Log::info($ex);
            $solution4Connection->rollBack();

            return false;
        }
    }

}

webserver/resources/views/solution/_4/tables/create.blade.php
@extends('layouts/app')

@section('title', '新增資料表')

@push('plugin-css')
{{-- multiselect CSS --}}
<link rel="stylesheet" href="https://unpkg.com/vue-multiselect@2.1.0/dist/vue-multiselect.min.css">
@endpush

@push('css')
<link href="{{ asset('assets/css/solution/_4/tables/create.css?v='.time()) }}" rel="stylesheet">
@endpush

@section('content')
<div class="main-content">

    <div class="container-fluid mt-5">
        <div class="col-12 nopadding">

            <div class="header">
                <div class="header-body">
                    <div class="row align-items-center mb-3">
                        <div class="col">

                            {{-- Pretitle --}}
                            <h6 class="header-pretitle">Create Table</h6>

                            {{-- Title --}}
                            <h1 class="header-title d-flex align-items-center">
                                <span>新增資料表</span>
                                <span class="ml-2 mr-2">-</span>
                                <span class="h2 nomargin">{{ $solution->name }}</span>
                            </h1>

                        </div>
                    </div> {{-- / .row --}}
                </div>
            </div>

            @include('components.forms.solution._4.tables.create')

        </div>
    </div>
</div>
@endsection


@push('plugin-js')
<script src="{{ asset('assets/plugins/dropzone/dropzone.min.js') }}"></script>
{{-- multiselect JS --}}
<script src="https://unpkg.com/vue-multiselect@2.1.0"></script>
<script src="{{ asset('assets/components/select/select.js') }}"></script>
{{-- jQuery mask JS --}}
<script src="{{ asset('assets/plugins/mask/jquery.mask.js') }}"></script>
@endpush


@push('js')
<script>
var args = {
    _token: "{{ csrf_token() }}",
    deployment: {{ $deployment->id }},
}
</script>
<script src="{{ asset('assets/js/solution/_4/tables/create.js?v='.time()) }}"></script>
@endpush

webserver/resources/views/solution/_4/tables/show.blade.php
@extends('layouts/app')

@section('title', '資料表內容')

@push('plugin-css')
{{-- multiselect CSS --}}
<link rel="stylesheet" href="https://unpkg.com/vue-multiselect@2.1.0/dist/vue-multiselect.min.css">
@endpush

@push('css')
<link href="{{ asset('assets/css/solution/_4/tables/show.css?v='.time()) }}" rel="stylesheet">
@endpush

@section('content')
<div class="main-content">

    <div class="container-fluid mt-5">
        <div class="col-12 nopadding">

            <div class="header">
                <div class="header-body">
                    <div class="row align-items-center mb-3">
                        <div class="col">

                            {{-- Pretitle --}}
                            <h6 class="header-pretitle">Table Info</h6>

                            {{-- Title --}}
                            <h1 class="header-title d-flex align-items-center flex-grow-1">
                                <span>資料表內容</span>
                                <span class="ml-2 mr-2">-</span>
                                <span class="h2 nomargin">{{ $solution->name }}</span>
                            </h1>

                        </div>
                    </div> {{-- / .row --}}
                </div>
            </div>

            <div v-cloak id="table-content">
                <div class="card">
                    <div class="card-body">
                        <h3 class="d-flex align-items-center mb-3">
                            <span class="mr-3">@{{ '# '+table.id }}</span>
                            <span class="flex-grow-1">@{{ table.name }}</span>

                            {{-- 資料筆數 --}}
                            <span class="data-counts position-relative small mr-3 pr-3">@{{ '資料筆數：'+table.dataCounts }}</span>

                            {{-- 類型 --}}
                            <span class="badge badge-soft-secondary">@{{ type[table.type] }}</span>

                            <div class="dropdown d-flex ml-3">
                                <a href="#" class="d-inline-flex align-items-center cursor-pointer dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <v-svg class="svg text-muted" src="{{ asset('assets/image/svg/light/ellipsis-v.svg') }}" width="22" height="22"></v-svg>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right p-0">
                                    <a href="javascript:void(0);" class="dropdown-item" @click="remove(table.id)">刪除資料表</a>
                                </div>
                            </div>
                        </h3>

                        <p class="text-muted m-0">@{{ table.description }}</p>

                    </div>

                    <div v-if="table.type == 'coupon'" class="d-flex align-items-center card-footer">
                        <span class="small line-height-initial mr-1">抽獎規則：</span>
                        <span class="badge badge-soft-secondary mr-2">@{{ table.settings.random ? '隨機領取' : '依序領取' }}</span>
                        <span class="badge badge-soft-secondary mr-2">@{{ table.settings.limit.active ? '領取數量限制：'+table.settings.limit.count : '無領取數量限制' }}</span>
                        <span class="badge badge-soft-secondary">@{{ table.settings.issueDatetime.active ? '領取時間限制：'+table.settings.issueDatetime.date.from+' ~ '+table.settings.issueDatetime.date.to+' , '+table.settings.issueDatetime.time.from+' ~ '+table.settings.issueDatetime.time.to : '無領取時間限制' }}</span>
                    </div>
                </div>


                {{-- 資料表 --}}
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col">

                                {{-- Search --}}
                                <form class="row align-items-center" @submit.prevent="search">
                                    <div class="col-auto pr-0">
                                        <span class="text-muted">
                                            <v-svg src="{{ asset('assets/image/svg/light/search.svg') }}" width="18" height="18"></v-svg>
                                        </span>
                                    </div>
                                    <div class="col">
                                        <input type="search" class="form-control form-control-flush search" placeholder="Search" v-model="query">
                                    </div>
                                </form>

                            </div>
                            <div class="col-auto">

                                {{-- Button --}}

                                <div class="dropdown">
                                    <button class="btn btn-sm btn-white" type="button" id="bulkActionDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">批次動作</button>
                                    <div class="dropdown-menu dropdown-menu-right font-size-0875" aria-labelledby="bulkActionDropdown">
                                        <!-- <a class="dropdown-item" href="javascript:void(0);">重新刊登（刪除wp文章）</a>
                                        <a class="dropdown-item" href="javascript:void(0);" @click="repost">重新刊登（不刪除wp文章）</a>
                                        <a class="dropdown-item" href="javascript:void(0);" @click="ignore">忽略文章</a>
                                        <a class="dropdown-item" href="javascript:void(0);">刪除wp文章（不重新刊登）</a> -->
                                    </div>
                                </div>

                            </div>
                        </div> {{-- / .row --}}
                    </div>
                    <div class="card-body p-0">
                        <div class="table-responsive position-relative">

                            <div :class="[is_loading ? 'd-flex' : 'd-none', 'loading-layout position-absolute justify-content-center align-items-center h-100 w-100 bg-secondary border-radius-bl-05 border-radius-br-05 z-index-1']">
                                <div class="spinner-grow text-secondary" role="status">
                                    <span class="sr-only">Loading...</span>
                                </div>
                            </div>

                            <table class="table table-sm table-nowrap card-table text-left">
                                <thead>
                                    <tr>
                                        <th v-for="column in table.columnList" class="text-transform-none">@{{ column }}</th>
                                    </tr>
                                </thead>
                                <tbody class="list">

                                    <tr v-for="row in rows">
                                        <td v-for="column in table.columnList" :class="[{'text-muted' : row[column] === null}]">@{{ row[column] === null ? 'NULL' : row[column] }}</td>
                                    </tr>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <nav v-cloak v-if="paginator.lastPage > 1" class="d-flex justify-content-center" aria-label="Page navigation">
                    <ul class="pagination">
                        <li v-if="paginator.currentPage >= 4" class="page-item" @click="changePage(paginator.currentPage - 3)">
                            <a class="page-link" href="javascript:void(0);" aria-label="Previous">
                                <span aria-hidden="true">...</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>

                        <li v-for="i in paginator.currentPage + 2" v-if="i >= 1 && i <= paginator.lastPage && i >= paginator.currentPage - 2" :class="['page-item', {'active': i == paginator.currentPage }]" @click="changePage(i)">
                            <a class="page-link" href="javascript:void(0);">@{{ i }}</a>
                        </li>

                        <li v-if="paginator.currentPage <= paginator.lastPage - 3" class="page-item" @click="changePage(paginator.currentPage + 3)">
                            <a class="page-link" href="javascript:void(0);" aria-label="Next">
                                <span aria-hidden="true">...</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                    </ul>
                </nav>







            </div>
        </div>

    </div>
</div>
@endsection


@push('plugin-js')

@endpush


@push('js')
<script>
var args = {
    _token: "{{ csrf_token() }}",
    deployment: {{ $deployment->id }},
    table: {!! $table->toJson() !!}
}
</script>
<script src="{{ asset('assets/js/solution/_4/tables/show.js?v='.time()) }}"></script>
@endpush