webserver/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function(){
    return view('home');
})->name('home');

//web
Route::group(['namespace'=>'Web'], function(){

    // deployment
    Route::group(['as'=>'deployment.', 'prefix'=>'deployment', 'namespace'=>'Deployment', 'middleware'=>['auth']], function(){
        Route::get('invitation/{code}', 'InvitationController@invitation')->name('invitation');
    });

    // paypal
    Route::group(['as'=>'paypal.', 'prefix'=>'paypal', 'namespace'=>'Paypal', 'middleware'=>['auth', 'role:developer']], function(){
        Route::group(['as'=>'agreement.', 'prefix'=>'agreement', 'namespace'=>'Agreement'], function(){
            Route::get('execute', 'AgreementController@execute')->name('execute');
        });
    });

    // billing
    Route::group(['as'=>'billing.', 'prefix'=>'billing', 'namespace'=>'Billing', 'middleware'=>['auth', 'role:developer']], function(){
        Route::get('/', 'BillingController@index')->name('index');
    });

    // solution
    Route::group(['as'=>'solution.', 'prefix'=>'solution', 'namespace'=>'Solution'], function(){
        Route::get('/', 'SolutionController@index')->name('index');

        Route::group(['prefix'=>'{solution}'], function(){
            Route::get('/', 'SolutionController@detail')->name('detail');

            //需要登入
            Route::group(['middleware'=>['auth']], function(){
                Route::get('deployments', 'SolutionController@deployments')->name('deployments');
                Route::get('getDeployments', 'SolutionController@getDeployments')->name('getDeployments');
                Route::get('deploy', 'SolutionController@deploy')->name('deploy');
            });
        });
    });

    // solution 4
    Route::group(['as'=>'solution.4.', 'prefix'=>'solution/4', 'namespace'=>'Solution\_4', 'middleware'=>['auth', 'setSolution:4']], function(){
        Route::post('/', 'SolutionController@store')->name('store');

        Route::group(['as'=>'deployment.', 'prefix'=>'deployment/{deployment}', 'middleware'=>['checkDeploymentInSolution', 'setSolutionDB', 'hasDeployment']], function(){
            Route::get('/', 'DeploymentController@show')->name('show');
            Route::get('getChartData', 'DeploymentController@getChartData')->name('getChartData');

            Route::group(['as'=>'iamAdmin.', 'prefix'=>'iamAdmin', 'namespace'=>'Deployment'], function(){
                Route::get('/', 'IamAdminController@index')->name('index');
                Route::get('getUsers', 'IamAdminController@getUsers')->name('getUsers');

                Route::post('assign', 'IamAdminController@assign')->name('assign');
                Route::post('invite', 'IamAdminController@invite')->name('invite');
                Route::delete('delete', 'IamAdminController@delete')->name('delete');
            });

            Route::group(['as'=>'richmenus.', 'prefix'=>'richmenus', 'namespace'=>'Deployment'], function(){
                Route::get('/', 'RichmenuController@index')->name('index');
                Route::get('getRichmenus', 'RichmenuController@getRichmenus')->name('getRichmenus');
                Route::get('create', 'RichmenuController@create')->name('create');
                Route::post('/', 'RichmenuController@store')->name('store');
                Route::get('queryForSelect', 'RichmenuController@queryForSelect')->name('queryForSelect');

                Route::group(['prefix'=>'{richmenuId}'], function(){
                    Route::get('/', 'RichmenuController@show')->name('show');
                    Route::delete('/', 'RichmenuController@delete')->name('delete');
                    Route::delete('deleteAll', 'RichmenuController@deleteAll')->name('deleteAll');
                    Route::get('edit', 'RichmenuController@edit')->name('edit');
                    Route::post('newVersion', 'RichmenuController@newVersion')->name('newVersion');
                    Route::post('toggelDefault', 'RichmenuController@toggelDefault')->name('toggelDefault');
                    Route::post('cancelBinding', 'RichmenuController@cancelBinding')->name('cancelBinding');
                    Route::post('switchVersion', 'RichmenuController@switchVersion')->name('switchVersion');
                    Route::get('getChartData', 'RichmenuController@getChartData')->name('getChartData');
                });
            });

            Route::group(['as'=>'welcomeMessages.', 'prefix'=>'welcomeMessages', 'namespace'=>'Deployment'], function(){
                Route::get('/', 'WelcomeMessageController@index')->name('index');
                Route::get('getWelcomeMessageCalendar', 'WelcomeMessageController@getWelcomeMessageCalendar')->name('getWelcomeMessageCalendar');
                Route::get('getWelcomeMessageList', 'WelcomeMessageController@getWelcomeMessageList')->name('getWelcomeMessageList');
                Route::get('create', 'WelcomeMessageController@create')->name('create');
                Route::post('/', 'WelcomeMessageController@store')->name('store');

                Route::group(['prefix'=>'{welcomeMessageId}'], function(){
                    Route::get('/', 'WelcomeMessageController@show')->name('show');
                    Route::post('toggleActive', 'WelcomeMessageController@toggleActive')->name('toggleActive');
                });
            });

            Route::group(['as'=>'autoAnswers.', 'prefix'=>'autoAnswers', 'namespace'=>'Deployment'], function(){
                Route::get('/', 'AutoAnswerController@index')->name('index');
                Route::get('getAutoAnswerCalendar', 'AutoAnswerController@getAutoAnswerCalendar')->name('getAutoAnswerCalendar');
                Route::get('getAutoAnswerList', 'AutoAnswerController@getAutoAnswerList')->name('getAutoAnswerList');
                Route::get('create', 'AutoAnswerController@create')->name('create');
                Route::post('/', 'AutoAnswerController@store')->name('store');

                Route::group(['prefix'=>'{autoAnswerId}'], function(){
                    Route::get('/', 'AutoAnswerController@show')->name('show');
                    Route::post('toggleActive', 'AutoAnswerController@toggleActive')->name('toggleActive');
                });
            });

            Route::group(['as'=>'broadcasts.', 'prefix'=>'broadcasts', 'namespace'=>'Deployment'], function(){
                Route::get('/', 'BroadcastController@index')->name('index');
                Route::get('getBroadcastCalendar', 'BroadcastController@getBroadcastCalendar')->name('getBroadcastCalendar');
                Route::get('getBroadcastList', 'BroadcastController@getBroadcastList')->name('getBroadcastList');
                Route::get('create', 'BroadcastController@create')->name('create');
                Route::post('/', 'BroadcastController@store')->name('store');

                Route::group(['prefix'=>'{broadcastId}'], function(){
                    Route::get('/', 'BroadcastController@show')->name('show');
                    Route::delete('/', 'BroadcastController@delete')->name('delete');
                });
            });

            Route::group(['as'=>'messagesPool.', 'prefix'=>'messagesPool', 'namespace'=>'Deployment'], function(){
                Route::get('/', 'MessagesPoolController@index')->name('index');
                Route::get('getMessages', 'MessagesPoolController@getMessages')->name('getMessages');
                Route::get('create', 'MessagesPoolController@create')->name('create');
                Route::post('store/message', 'MessagesPoolController@storeMessage')->name('storeMessage');
                Route::post('store/template', 'MessagesPoolController@storeTemplate')->name('storeTemplate');
                Route::get('queryForSelect', 'MessagesPoolController@queryForSelect')->name('queryForSelect');

                Route::group(['prefix'=>'{messageId}'], function(){
                    Route::get('/', 'MessagesPoolController@show')->name('show');
                    Route::get('edit', 'MessagesPoolController@edit')->name('edit');
                    Route::post('newMessageVersion', 'MessagesPoolController@newMessageVersion')->name('newMessageVersion');
                    Route::post('newTemplateVersion', 'MessagesPoolController@newTemplateVersion')->name('newTemplateVersion');
                    Route::post('switchVersion', 'MessagesPoolController@switchVersion')->name('switchVersion');
                    Route::delete('deleteAll', 'MessagesPoolController@deleteAll')->name('deleteAll');
                    Route::get('getMessage', 'MessagesPoolController@getMessage')->name('getMessage');
                });
            });

            Route::group(['as'=>'keywords.', 'prefix'=>'keywords', 'namespace'=>'Deployment'], function(){
                Route::get('/', 'KeywordController@index')->name('index');
                Route::get('getKeywords', 'KeywordController@getKeywords')->name('getKeywords');
                Route::get('getChartData', 'KeywordController@getChartData')->name('getChartData');
                Route::get('create', 'KeywordController@create')->name('create');
                Route::get('getRichmenu', 'KeywordController@getRichmenu')->name('getRichmenu');
                Route::post('/', 'KeywordController@store')->name('store');
                Route::get('queryForSelect', 'KeywordController@queryForSelect')->name('queryForSelect');

                Route::group(['prefix'=>'{keywordId}'], function(){
                    Route::get('/', 'KeywordController@show')->name('show');
                    Route::get('edit', 'KeywordController@edit')->name('edit');

webserver/resources/views/layouts/navbars/main/sidebars/billing.blade.php
{{-- Heading --}}
<h6 class="navbar-heading">Billing</h6>

<ul id="dashboardSliders" class="navbar-nav">
  <li class="nav-item">
    <a class="nav-link" href="#">
      <span>總覽</span>
    </a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="#">
      <span>付款方式</span>
    </a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="#">
      <span>帳單列表</span>
    </a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="#">
      <span>交易記錄</span>
    </a>
  </li>

</ul>

webserver/resources/views/layouts/navbars/main/sidebars/solution_1.blade.php
{{-- Heading --}}
<h6 class="navbar-heading">Deployment</h6>

<ul id="dashboardSliders" class="navbar-nav">
  <li class="nav-item">
    <a class="nav-link" href="{{ route('solution.1.deployment.show', $deployment) }}">
      <span>部署儀表板</span>
    </a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{{ route('solution.1.deployment.settings', $deployment) }}">
      <span>部署設定</span>
    </a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{{ route('solution.1.deployment.crawlers', $deployment) }}">
      <span>爬蟲管理</span>
    </a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{{ route('solution.1.deployment.posts', $deployment) }}">
      <span>文章管理</span>
    </a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{{ route('solution.1.deployment.logs', $deployment) }}">
      <span>系統訊息記錄</span>
    </a>
  </li>

</ul>

webserver/resources/views/layouts/navbars/main/sidebars/solution_2.blade.php
{{-- Heading --}}
<h6 class="navbar-heading">Deployment</h6>

<ul id="dashboardSliders" class="navbar-nav">
  <li class="nav-item">
    <a class="nav-link" href="{{ route('solution.2.deployment.show', $deployment) }}">
      <span>部署儀表板</span>
    </a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{{ route('solution.2.deployment.settings', $deployment) }}">
      <span>部署設定</span>
    </a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{{ route('solution.2.deployment.wordpress', $deployment) }}">
      <span>Wordpress設定</span>
    </a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{{ route('solution.2.deployment.crawlers', $deployment) }}">
      <span>爬蟲管理</span>
    </a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{{ route('solution.2.deployment.posts', $deployment) }}">
      <span>文章管理</span>
    </a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{{ route('solution.2.deployment.logs', $deployment) }}">
      <span>系統訊息記錄</span>
    </a>
  </li>
</ul>

webserver/resources/views/layouts/navbars/main/sidebars/solution_3.blade.php
{{-- Heading --}}
<h6 class="navbar-heading">Deployment</h6>

<ul id="dashboardSliders" class="navbar-nav">
  <li class="nav-item">
    <a class="nav-link" href="#">
      <span>個人帳號分析</span>
    </a>
  </li>

  <li class="nav-item">
    <a class="nav-link collapsed" href="#sidebarFans" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarCourses">
      <span>粉絲分析</span>
      <span class="arrow">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512">
          <path fill="currentColor" d="M119.5 326.9L3.5 209.1c-4.7-4.7-4.7-12.3 0-17l7.1-7.1c4.7-4.7 12.3-4.7 17 0L128 287.3l100.4-102.2c4.7-4.7 12.3-4.7 17 0l7.1 7.1c4.7 4.7 4.7 12.3 0 17L136.5 327c-4.7 4.6-12.3 4.6-17-.1z"></path>
        </svg>
      </sapn>
    </a>
    <div class="collapse" id="sidebarFans">
      <ul class="nav nav-sm flex-column">
        <li class="nav-item">
          <a href="#" class="nav-link">
            <span>整體粉絲分析</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <span>單一粉絲分析</span>
          </a>
        </li>
      </ul>
    </div>
  </li>

  <li class="nav-item">
    <a class="nav-link collapsed" href="#sidebarNotFans" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarCourses">
      <span>非粉絲分析</span>
      <span class="arrow">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512">
          <path fill="currentColor" d="M119.5 326.9L3.5 209.1c-4.7-4.7-4.7-12.3 0-17l7.1-7.1c4.7-4.7 12.3-4.7 17 0L128 287.3l100.4-102.2c4.7-4.7 12.3-4.7 17 0l7.1 7.1c4.7 4.7 4.7 12.3 0 17L136.5 327c-4.7 4.6-12.3 4.6-17-.1z"></path>
        </svg>
      </sapn>
    </a>
    <div class="collapse" id="sidebarNotFans">
      <ul class="nav nav-sm flex-column">
        <li class="nav-item">
          <a href="#" class="nav-link">
            <span>整體非粉絲分析</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <span>單一非粉絲分析</span>
          </a>
        </li>
      </ul>
    </div>
  </li>

  <li class="nav-item">
    <a class="nav-link collapsed" href="#sidebarPosts" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarCourses">
      <span>貼文分析</span>
      <span class="arrow">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512">
          <path fill="currentColor" d="M119.5 326.9L3.5 209.1c-4.7-4.7-4.7-12.3 0-17l7.1-7.1c4.7-4.7 12.3-4.7 17 0L128 287.3l100.4-102.2c4.7-4.7 12.3-4.7 17 0l7.1 7.1c4.7 4.7 4.7 12.3 0 17L136.5 327c-4.7 4.6-12.3 4.6-17-.1z"></path>
        </svg>
      </sapn>
    </a>
    <div class="collapse" id="sidebarPosts">
      <ul class="nav nav-sm flex-column">
        <li class="nav-item">
          <a href="#" class="nav-link">
            <span>整體貼文分析</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <span>單一貼文分析</span>
          </a>
        </li>
      </ul>
    </div>
  </li>

  <li class="nav-item">
    <a class="nav-link collapsed" href="#sidebarAccounts" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarCourses">
      <span>關注帳號分析</span>
      <span class="arrow">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512">
          <path fill="currentColor" d="M119.5 326.9L3.5 209.1c-4.7-4.7-4.7-12.3 0-17l7.1-7.1c4.7-4.7 12.3-4.7 17 0L128 287.3l100.4-102.2c4.7-4.7 12.3-4.7 17 0l7.1 7.1c4.7 4.7 4.7 12.3 0 17L136.5 327c-4.7 4.6-12.3 4.6-17-.1z"></path>
        </svg>
      </sapn>
    </a>
    <div class="collapse" id="sidebarAccounts">
      <ul class="nav nav-sm flex-column">
        <li class="nav-item">
          <a href="#" class="nav-link">
            <span>...</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <span>...</span>
          </a>
        </li>
      </ul>
    </div>
  </li>



</ul>

webserver/resources/views/layouts/navbars/main/sidebars/solution_4.blade.php
{{-- Heading --}}
<h6 class="navbar-heading">Deployment</h6>

<ul id="dashboardSliders" class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link" href="{{ route('solution.4.deployment.show', $deployment) }}">
            <span>機器人儀表板</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{{ route('solution.4.deployment.richmenus.index', $deployment) }}">
            <span>主選單設定</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#sidebarMessage" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarMessage">
            <span>訊息設定</span>
            <span class="arrow">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512">
                    <path fill="currentColor" d="M119.5 326.9L3.5 209.1c-4.7-4.7-4.7-12.3 0-17l7.1-7.1c4.7-4.7 12.3-4.7 17 0L128 287.3l100.4-102.2c4.7-4.7 12.3-4.7 17 0l7.1 7.1c4.7 4.7 4.7 12.3 0 17L136.5 327c-4.7 4.6-12.3 4.6-17-.1z"></path>
                </svg>
            </sapn>
        </a>
        <div class="collapse" id="sidebarMessage">
            <ul class="nav nav-sm flex-column">
                <li class="nav-item">
                    <a href="{{ route('solution.4.deployment.welcomeMessages.index', $deployment) }}" class="nav-link">
                        <span>歡迎訊息</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('solution.4.deployment.autoAnswers.index', $deployment) }}" class="nav-link">
                        <span>自動回覆</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('solution.4.deployment.broadcasts.index', $deployment) }}" class="nav-link">
                        <span>推播訊息</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('solution.4.deployment.messagesPool.index', $deployment) }}" class="nav-link">
                        <span>訊息庫</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('solution.4.deployment.keywords.index', $deployment) }}" class="nav-link">
                        <span>關鍵字</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('solution.4.deployment.scripts.index', $deployment) }}" class="nav-link">
                        <span>訊息腳本</span>
                    </a>
                </li>
            </ul>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{{ route('solution.4.deployment.liffs.index', $deployment) }}">
            <span>LIFF App</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{{ route('solution.4.deployment.tags.index', $deployment) }}">
            <span>行為標籤</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{{ route('solution.4.deployment.tables.index', $deployment) }}">
            <span>資料庫</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#sidebarUser" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarUser">
            <span>好友管理</span>
            <span class="arrow">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512">
                    <path fill="currentColor" d="M119.5 326.9L3.5 209.1c-4.7-4.7-4.7-12.3 0-17l7.1-7.1c4.7-4.7 12.3-4.7 17 0L128 287.3l100.4-102.2c4.7-4.7 12.3-4.7 17 0l7.1 7.1c4.7 4.7 4.7 12.3 0 17L136.5 327c-4.7 4.6-12.3 4.6-17-.1z"></path>
                </svg>
            </sapn>
        </a>
        <div class="collapse" id="sidebarUser">
            <ul class="nav nav-sm flex-column">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('solution.4.deployment.users.index', $deployment) }}">
                        <span>好友列表</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('solution.4.deployment.groups.index', $deployment) }}">
                        <span>好友群組</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('solution.4.deployment.chatroom.index', $deployment) }}">
                        <span>聊天室</span>
                    </a>
                </li>
            </ul>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#sidebarSettings" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarSettings">
            <span>部署設定</span>
            <span class="arrow">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512">
                    <path fill="currentColor" d="M119.5 326.9L3.5 209.1c-4.7-4.7-4.7-12.3 0-17l7.1-7.1c4.7-4.7 12.3-4.7 17 0L128 287.3l100.4-102.2c4.7-4.7 12.3-4.7 17 0l7.1 7.1c4.7 4.7 4.7 12.3 0 17L136.5 327c-4.7 4.6-12.3 4.6-17-.1z"></path>
                </svg>
            </sapn>
        </a>
        <div class="collapse" id="sidebarSettings">
            <ul class="nav nav-sm flex-column">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('solution.4.deployment.iamAdmin.index', $deployment) }}">
                        <span>IAM</span>
                    </a>
                </li>
            </ul>
        </div>
    </li>

</ul>

webserver/resources/views/layouts/navbars/main/sidebars/solution_5.blade.php
{{-- Heading --}}
<h6 class="navbar-heading">Deployment</h6>

<ul id="dashboardSliders" class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link" href="{{ route('solution.5.deployment.show', $deployment) }}">
            <span>EIP 儀表板</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{{ route('solution.5.deployment.organization.index', $deployment) }}">
            <span>組織架構</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{{ route('solution.5.deployment.show', $deployment) }}">
            <span>個人資料</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#sidebarDocument" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarDocument">
            <span>文件管理</span>
            <span class="arrow">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512">
                    <path fill="currentColor" d="M119.5 326.9L3.5 209.1c-4.7-4.7-4.7-12.3 0-17l7.1-7.1c4.7-4.7 12.3-4.7 17 0L128 287.3l100.4-102.2c4.7-4.7 12.3-4.7 17 0l7.1 7.1c4.7 4.7 4.7 12.3 0 17L136.5 327c-4.7 4.6-12.3 4.6-17-.1z"></path>
                </svg>
            </sapn>
        </a>
        <div class="collapse" id="sidebarDocument">
            <ul class="nav nav-sm flex-column">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('solution.5.deployment.show', $deployment) }}">
                        <span>文件列表</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('solution.5.deployment.show', $deployment) }}">
                        <span>簽署文件</span>
                    </a>
                </li>
            </ul>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{{ route('solution.5.deployment.show', $deployment) }}">
            <span>檔案資源</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#sidebarBooking" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarBooking">
            <span>預約系統</span>
            <span class="arrow">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512">
                    <path fill="currentColor" d="M119.5 326.9L3.5 209.1c-4.7-4.7-4.7-12.3 0-17l7.1-7.1c4.7-4.7 12.3-4.7 17 0L128 287.3l100.4-102.2c4.7-4.7 12.3-4.7 17 0l7.1 7.1c4.7 4.7 4.7 12.3 0 17L136.5 327c-4.7 4.6-12.3 4.6-17-.1z"></path>
                </svg>
            </sapn>
        </a>
        <div class="collapse" id="sidebarBooking">
            <ul class="nav nav-sm flex-column">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('solution.5.deployment.show', $deployment) }}">
                        <span>會議室</span>
                    </a>
                </li>
            </ul>
        </div>
    </li>

</ul>